import type { Metadata } from "next";
import { Cinzel, Cormorant } from "next/font/google";
import "./globals.css";

export const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cinzel",
});

export const cormorant = Cormorant({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${cormorant.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
